# Data Exploration & first visualization ideas

# First Step: Exploring the data 

## Reducing food’s environmental impacts through producers and consumers - Poore & Nemecek, 2018

### Dataset Info
Poore, J.; Nemecek, T. (2018). Reducing food’s environmental impacts through producers and consumers. Science, 360(6392), 987–992. doi:10.1126/science.aaq0216  

Link: https://www.science.org/doi/10.1126/science.aaq0216

This dataset covers data from approx. 38,700 commercially viable farms in 119 countries and 40 products representing ~90% of global protein and calorie consumption.

The meta-analysis five important environmental impact indicators:

- land use
- freshwater withdrawals weighted by local water scarcity
- GHG (greenhouse gas)
- acidifying 
- eutrophying emissions (runoff of excess nutrients into thesurrounding environment and waterways, which affect and polluteecosystems - measured in grams of phosphateequivalents (PO₄eq))

-> interesting for the Data-Storytelling: Land Use, Freshwater Use & GHG emissions

### Working with the data
Starting point - overview over the overall impact of food on the climate

"Today’s food supply chain creates ~13.7 billion
metric tons of carbon dioxide equivalents (CO2eq),
26% of anthropogenic (man-made) GHG emissions."

Possible visualization: Pie Chart




## Alternative protein company database - Good Food Institute 

### Dataset Info
Link: https://gfi.org/resource/alternative-protein-company-database/#manufacturers-and-brands


### Working with the data

In the data set, there is "cultivated meat" under the category "protein category". Maybe filter to only "plant-based"?

Interesting metrics for the Storyline:
- company focus (e.g. meat, dairy alternative)
- Country/ region
- year founded 

Possible insights:
- growth in recent years (e.g. after 2010)
- there are a lot of companys providing alternatives 
- maybe comparing countries?
- indicating/ fitering by product type 
- (There are Logos in the database, could be cool to use?)


## Consumption of meat per person in germany from 2010 to 2022 - BMEL

## Dataset Info 

Link: https://www.bmel-statistik.de/ernaehrung-fischerei/versorgungsbilanzen/fleisch

## Working with the data 

Interesting metric: "Verzehr pro Kopf"

